server:
  port: 8691

product.host: http://localhost:8688
customer.host: http://localhost:8689

aws:
  sqs:
    close-cart:
      name: local-payment-cart-closed-queue

spring:
  cloud:
    aws:
      endpoint: http://localhost:4566
      region:
        static: us-east-1