aws:
  sqs:
    close-cart:
      name: prd-payment-cart-closed-queue

  sns:
    created-payment:
      name: prd-payment-created-topic
    done-payment:
      name: prd-payment-done-topic

spring:
  cloud:
    aws:
      region:
        static: us-east-1
  data:
    mongodb:
      uri: #defined at task definition
      database: paymentdb
      port: 27017